# Generated by Django 3.2 on 2021-08-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_article_articl'),
    ]

    operations = [
        migrations.AddField(
            model_name='articl',
            name='category',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
