# Generated by Django 3.2 on 2021-08-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug_cat', models.SlugField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='articl',
            name='category',
        ),
        migrations.AddField(
            model_name='articl',
            name='category',
            field=models.ManyToManyField(to='blog.category'),
        ),
    ]
